kind = "web"
previewPath = "/"
title = "Peminjaman Lab Poltekkes Tasikmalaya"
version = "1.0.0"
id = "artifacts/lab-peminjaman"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 24448
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/lab-peminjaman run dev"

[services.env]
PORT = "24448"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/lab-peminjaman", "run", "build"]
publicDir = "artifacts/lab-peminjaman/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
